import React,{useEffect} from "react";
import useAxios from "../../../Services/servicecall";
import CF_activeUserdetails from "../../../Services/activeUserdetails";
const PrintTable = ({
  columns,
  rows,
  title,
  subtitle,
  printRequest,
  onDone,
}) => {
  const { postData } = useAxios();

  const printDate = new Date().toLocaleDateString();
  const printTime = new Date().toLocaleTimeString();

 const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
            @media print {
            @page { margin: 20px; }
            body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
            .print-header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
            .print-title { font-size: 24px; font-weight: bold; color: #333; margin-bottom: 5px; }
            .print-subtitle { font-size: 16px; color: #666; margin-bottom: 10px; }
            .print-meta { display: flex; justify-content: space-between; margin-bottom: 20px; font-size: 12px; color: #555; }
            .print-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .print-table th { background-color: #f4f6f8; color: #333; font-weight: bold; padding: 10px; text-align: left; border: 1px solid #ddd; }
            .print-table td { padding: 8px 10px; border: 1px solid #ddd; font-size: 12px; }
            .print-table tr:nth-child(even) { background-color: #f9f9f9; }
            .print-footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #ddd; font-size: 11px; color: #777; text-align: center; }
            .status-Active { color: #28a745; font-weight: bold; }
            .status-Deactive { color: #dc3545; font-weight: bold; }
          }
           @media print {
  @page {
    size: A4;
    margin: 20mm;
  }

  body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
  }

  thead {
    display: table-header-group;
  }

  tfoot {
    display: table-footer-group;
  }

  tr {
    page-break-inside: avoid;
  }
}


        </style>
      </head>
      <body>
        <div class="print-header">
          <div class="print-title">${title}</div>
          <div class="print-subtitle">${subtitle}</div>
        </div>

        <div class="print-meta">
          <div>
            <strong>Report Date:</strong> ${printDate}<br>
            <strong>Report Time:</strong> ${printTime}<br>
          </div>
          <div>
            <strong>Total Records:</strong> ${rows.length}<br>
            <strong>Generated By:</strong> ${printRequest.ActiveUserDetails.sUsername || "N/A"}
          </div>
        </div>

        <table class="print-table">
          <thead>
            <tr>
              ${columns.map((col) => `<th>${col.label}</th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${rows
              .map((row) => {
                return `<tr>
                  ${columns
                    .map((col) => {
                      const val = row[col.key] ?? "-";
                      const cls = col.key === "status" ? `status-${val}` : "";
                      return `<td class="${cls}">${val}</td>`;
                    })
                    .join("")}
                </tr>`;
              })
              .join("")}
          </tbody>
                  <tfoot>
  <tr>
    <td colspan="${columns.length}" class="print-footer">
      Generated by SDMS - ${title} Module
    </td>
  </tr>
</tfoot>
        </table>


      </body>
      </html>
    `;

useEffect(() => {
  const printWindow = window.open('', '_blank', 'width=1200,height=800,left=100,top=50');

  if (!printWindow) {
    console.error("Popup blocked");
    return;
  }

  printWindow.document.open();
  printWindow.document.write(printContent);
  printWindow.document.close();

  printWindow.onload = () => {
    setTimeout(() => {
      printWindow.focus();
      printWindow.print();
    }, 300);
  };

  printWindow.onafterprint = async () => {
    try {
      await postData("basemaster/print", printRequest);
      console.log("Print API success");
    } catch (err) {
      console.error("Print API error:", err);
    } finally {
      printWindow.close();
      onDone?.();
    }
  };
}, []);

  return null;
};

export default PrintTable;


